-- Medicao de custo de IA por endpoint/acao/usuario.
-- Aplicar depois da 035. Somente service_role escreve ou le.

BEGIN;

-- O CMS agora salva pelo /api/admin, que sanitiza no servidor. Revogar a
-- escrita direta impede contornar essa fronteira chamando o PostgREST.
revoke insert, update, delete on public.blog_posts from authenticated;

create table if not exists public.ai_usage_events (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete set null,
  endpoint text not null check (char_length(endpoint) between 1 and 80),
  action text not null check (char_length(action) between 1 and 80),
  model text not null check (char_length(model) between 1 and 100),
  prompt_version text,
  input_tokens bigint not null default 0 check (input_tokens >= 0),
  output_tokens bigint not null default 0 check (output_tokens >= 0),
  cache_creation_input_tokens bigint not null default 0 check (cache_creation_input_tokens >= 0),
  cache_read_input_tokens bigint not null default 0 check (cache_read_input_tokens >= 0),
  estimated_cost_usd numeric(14,8) not null default 0 check (estimated_cost_usd >= 0),
  provider_request_id text,
  created_at timestamptz not null default now()
);

create index if not exists ai_usage_events_created_at_idx
  on public.ai_usage_events (created_at desc);
create index if not exists ai_usage_events_endpoint_created_at_idx
  on public.ai_usage_events (endpoint, created_at desc);
create index if not exists ai_usage_events_user_created_at_idx
  on public.ai_usage_events (user_id, created_at desc)
  where user_id is not null;

alter table public.ai_usage_events enable row level security;
revoke all on table public.ai_usage_events from PUBLIC, anon, authenticated;
grant all on table public.ai_usage_events to service_role;
grant usage, select on sequence public.ai_usage_events_id_seq to service_role;

create or replace function public.cleanup_ai_usage_events(p_days integer default 180)
returns integer
language plpgsql
security definer
set search_path = public
as $$
declare
  removed integer;
begin
  if p_days < 30 or p_days > 730 then
    raise exception 'p_days fora do intervalo permitido';
  end if;
  delete from public.ai_usage_events where created_at < now() - make_interval(days => p_days);
  get diagnostics removed = row_count;
  return removed;
end;
$$;

revoke all on function public.cleanup_ai_usage_events(integer) from public, anon, authenticated;
grant execute on function public.cleanup_ai_usage_events(integer) to service_role;

create or replace function public.ai_usage_summary(p_days integer default 30)
returns table (
  endpoint text,
  action text,
  model text,
  requests bigint,
  unique_users bigint,
  input_tokens bigint,
  output_tokens bigint,
  cache_creation_input_tokens bigint,
  cache_read_input_tokens bigint,
  estimated_cost_usd numeric
)
language sql
stable
security definer
set search_path = public
as $$
  select
    e.endpoint,
    e.action,
    e.model,
    count(*)::bigint,
    count(distinct e.user_id)::bigint,
    coalesce(sum(e.input_tokens), 0)::bigint,
    coalesce(sum(e.output_tokens), 0)::bigint,
    coalesce(sum(e.cache_creation_input_tokens), 0)::bigint,
    coalesce(sum(e.cache_read_input_tokens), 0)::bigint,
    coalesce(sum(e.estimated_cost_usd), 0)::numeric
  from public.ai_usage_events e
  where e.created_at >= now() - make_interval(days => greatest(1, least(p_days, 365)))
  group by e.endpoint, e.action, e.model
  order by coalesce(sum(e.estimated_cost_usd), 0) desc;
$$;

revoke all on function public.ai_usage_summary(integer) from public, anon, authenticated;
grant execute on function public.ai_usage_summary(integer) to service_role;

COMMIT;
